files = dir('*.fig');

asTikz = @(file) strrep(file.name, '.fig','.tikz');

for file = files(:)'
    fprintf(' %s \t -> \t %s \n', file.name, asTikz(file));
    
    hFig = open(file.name);
    finallyCloseFigure = onCleanup(@() close(hFig));
    try
        matlab2tikz(asTikz(file), 'figurehandle', hFig, ...
                    'width', '\figurewidth', ...
                    'height', '\figureheight', ...
                    'standalone', false, ...
                    'externalData', true, ...
                    'relativeDataPath', '\thisDir/figs/', ...
                    'showInfo', false);
    catch ME
        fprintf(2,'Error "%s" during conversion of %s\n%s\n\n', ...
                ME.identifier, file.name, getReport(ME));
    end
end
